version: '2'
services:
  appdb:
    image: postgres:9.3
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  possum:
    image: conjurinc/possum
    ports:
      - "3030:80"
    command: server -a example -f /src/policy.yml
    volumes:
      - .:/src
    environment:
      DATABASE_URL: postgres://postgres@possumdb/postgres
      POSSUM_ADMIN_PASSWORD: secret
      POSSUM_DATA_KEY:
    depends_on:
      - possumdb

  possumdb:
    image: postgres:9.3
